### ISSUE TITLE
The stdout data for likes and comments seems to be incomplete

### ISSUE THREAD

**Issue by MycChiu** [KyleAMathews/facebook-export#5]
first of all, thanks for the great work! Saved me tons of time. 
I realized that the default setting doesn't result in complete data for the likes and comments, it will ask you to page through the likes and comments if the post's likes/comments exceeds a certain number. Please see the stack post for the work-around.
http://stackoverflow.com/questions/6984526/facebook-graph-api-get-like-count-on-page-group-photos

edit:
nvm, I just saw your comment in fetch_posts.coffee, please close this issue

**Comment by KyleAMathews** [comment]
:)
