### ISSUE TITLE
People with 2 surnames don't appear in the results

### ISSUE THREAD

**Issue by Wojtab** [KyleAMathews/facebook-export#9]
As the title says - if person has 2 surnames their posts are not pulled, they also don't appear in the members list.(I think it's facebook api bug, because they also don't show up in Graph API Explorer, but I can't report api bugs)

**Comment by KyleAMathews** [comment]
Is there anything actionable we can do here?

**Comment by Wojtab** [comment]
I'm not sure, but you as a Facebook developer can submit bug report to them, because your program is affected.

**Comment by KyleAMathews** [comment]
Haha, I'm just a regular peon like you :) I don't work at Facebook. This is just a little fun / sometimes useful side project. Feel free to use this issue to email Facebook support about the issue.
